name: Run Discord Bot

on:
  schedule:
    - cron: "0 23 * * *"   # 한국 시간 08:00 AM (KST) - 하루 동안 실행 시작
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install discord.py
          
      - name: Run bot in background
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: nohup python bot.py &
